server.port: 4808

server.request:
  maxBodySize: 10mb
  maxFileSize: 10mb

server.http:
  coreThreads: 2
  maxThreads: 16

solon.task:
  execution:
    pool:
      size: 8
  scheduling:
    pool:
      size: 4

solon.app:
  name: "soloncode"
  title: "SolonCode"

solon.logging.appender:
  console:
    enable: false
  file:
    enable: false
    level: INFO
    name: "${user.home}/.soloncode/workspaces/${soloncode.wskey}/logs/${solon.app.name}"
    extension: ".log"
    maxFileSize: "10 MB"
    maxHistory: "7" #单位：天
    totalSizeCap: "200 MB"

solon:
  logging:
    logger:
      "org.eclipse.jetty":
        level: WARN
      "io.modelcontextprotocol":
        level: INFO
